version: '3'
services:
  DB:
    hostname: nest-template
    image: postgres:13-alpine
    container_name: nest-template-DB
    networks:
      - nest-template-network
    restart: on-failure
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=temp
      - POSTGRES_USER=temp
      - POSTGRES_PASSWORD=q1w2e3
    volumes:
      - ./postgresql-data:/var/lib/postgresql/data
  redis:
    hostname: nest-template
    image: redis:6-alpine
    container_name: nest-template-redis
    networks:
      - nest-template-network
    restart: on-failure
    ports:
      - 6379:6379

networks:
  nest-template-network:
